### PR TITLE
Add a default file to DiskFileService

### PR DESCRIPTION
**Pull request by cjmurph**
Added a default file to be served from the file service if none is specified by the client (e.g. index.html)

### CODE REVIEW

**Comment by jgauffin** [comment]
Thank you for your pull request! 

Some small issues:

* Name the property `DefaultHtmlFile` to make it clear that it should not contain HTML but a file name
* Properties should be placed after the constructors
* Methods in C# are with `PascalCase` i.e. `GetDefaultFileName`

**Comment by cjmurph** [comment]
Hi, no worries, I'll make the changes. 
It's worth noting however that private methods should be camelCase not PascalCase, though if that's what you've chosen to do in your project I'll adopt it. I didn't notice sorry.

**Comment by jgauffin** [comment]
No, private methods should not be camelCase. Look at the .NET Design Guidelines: https://msdn.microsoft.com/en-us/library/ms229012(v=vs.110).aspx

**Comment by jgauffin** [comment]
You forgot this one:

```csharp
  if (fullPath == _basePath)
           fullPath = getDefaultFile();
```

Don't think that the code compiles as is?

**Comment by cjmurph** [comment]
Indeed! Sorry, I was sitting at the airport and my flight got called. I shouldn't have synced up until I built.

You win on the guidelines. Funny, every project I've been involved in with c sharp has adopted the camelCase private method standard, They all went by a document I'm struggling to find now. You live and learn. I have a lot of re-factoring to do today!

**Pull request merged**
